### PR TITLE
Closes #44 - Fixed tests, included error stack traces in console output.

### LINKED ISSUE #44: Fix occasional failure of system tests
The system tests occasionally fail because they try to read metrics from the OpenCensus API which are somehow not available. Strangely, the recording in inspectIT is executed prior to the tests, however it seems like the OpenCensus buffers the recorded data somewhere before it gets flushed and visible for the tests.

Currently we have added a sleep as a workaround, which however does not always work. We need to find a way to trigger the flushing of the metrics prior to performing test asertions. @ivansenic suggested that we could try to execute a synchronous get agains the prometheus endpoint. The hope is that this triggers the flushing of the metrics so that they are available for the tests.

### PR DESCRIPTION
**Pull request by JonasKunz**

### CODE REVIEW

File: inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/TestUtils.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import java.util.concurrent.atomic.AtomicBoolean;
+
+public class TestUtils {
+
+    /**
+     * Opencensus internally manages a queue of events.
+     * We simply add a event to the queue and wait unti it is processed.
+     */
+    public static void waitForOpenCensusQueueToBeProcessed() {
+        AtomicBoolean entryProcessed = new AtomicBoolean(false);
```
Comment (ivansenic) [inline inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/TestUtils.java]: why here both Atomic and sync? simply have atomic only and instead of wait/notify do a small sleep until you get true from the atomic?

File: inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ClassLoaderMetricsSysTest.java [hunk 2]
```diff
@@ -7,32 +7,36 @@
...
-
-        //ensure that the values are sane
-        long loadedVal = ((AggregationData.LastValueDataLong) loaded.getValue()).getLastValue();
-        long unloadedVal = ((AggregationData.LastValueDataLong) unloaded.getValue()).getLastValue();
-
-        assertThat(loadedVal).isLessThanOrEqualTo(ManagementFactory.getClassLoadingMXBean().getTotalLoadedClassCount());
-        assertThat(unloadedVal).isLessThanOrEqualTo(ManagementFactory.getClassLoadingMXBean().getUnloadedClassCount());
+    public void testClassLoaderMetricCapturing() {
+        await().atMost(5, TimeUnit.SECONDS).untilAsserted(() -> {
+            ViewData loadedData = viewManager.getView(View.Name.create("jvm/classes/loaded"));
```
Comment (ivansenic) [inline inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ClassLoaderMetricsSysTest.java]: should you also call here  `TestUtils.waitForOpenCensusQueueToBeProcessed();` first? At least you are ensuring that queue is drained before you check? Maybe actually outside the await()!

Comment (ivansenic) [reply inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ClassLoaderMetricsSysTest.java]: ahh ok this is fixed with:

```
@BeforeEach
    void flushMetrics() {
```

File: inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/SpringConfiguration.java [hunk 3]
```diff
@@ -1,27 +1,47 @@
...
             t.setName("inspectit-thread-" + threadCount.getAndIncrement());
             return t;
         });
+        return activeExecutor;
+    }
+
+    @PreDestroy
+    void destroy() {
+        if (activeExecutor != null) {
+            activeExecutor.shutdownNow();
```
Comment (ivansenic) [inline inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/SpringConfiguration.java]: not related to the test, but do we have a shutdown of the executor created in the context?

File: inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/SpringTestBase.java [hunk 4]
```diff
@@ -119,8 +119,9 @@ public void initialize(ConfigurableApplicationContext ctx) {
      * @param level the level to compare against.
      */
     public void assertNoLogsOfLevelOrGreater(Level level) {
+        //TODO: remove ignore for existing view errors as soon as we are able to unregister views in OpenCensus
         verify(env.mockAppender, times(0)).doAppend(argThat(
-                (le) -> le.getLevel().isGreaterOrEqual(level)));
+                (le) -> le.getLevel().isGreaterOrEqual(level) && !le.getMessage().contains("View with the name ")));
```
Comment (ivansenic) [inline inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/SpringTestBase.java]: I would prefer that we log the other message on `INFO` and don't do this check?!

Comment (ivansenic) [reply inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/SpringTestBase.java]: ahh I see level is parameter here.. then let's use Slf4j markers! you can create a marker that should be ignored and can be used in tests..

File: inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/GCMetricsSysTest.java [hunk 5]
```diff
@@ -81,7 +81,7 @@ public void testGCPauseCapturing() throws Exception {
                 .findFirst().get();
 
 
-        assertThat(((AggregationData.SumDataLong) minorTime.getValue()).getSum()).isGreaterThan(0);
+        assertThat(((AggregationData.SumDataLong) minorTime.getValue()).getSum()).isGreaterThanOrEqualTo(0);
         assertThat(((AggregationData.SumDataLong) majorTime.getValue()).getSum()).isGreaterThan(0);
```
Comment (mariusoe) [inline inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/GCMetricsSysTest.java]: Can it happen, that we had only minor GCs but not a major one, so this would be 0? Or is the notification only sent on major ones?

File: inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/TestUtils.java (hunk 1 above)
Comment (JonasKunz) [reply inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/TestUtils.java]: Atomic is just used to have a settable boolean.

File: inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/GCMetricsSysTest.java (hunk 5 above)
Comment (JonasKunz) [reply inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/GCMetricsSysTest.java]: I don't think we experienced this yet.. what I experienced here was that my minorgc was so fast that it had 0ms pause time.. that's why I adjusted the check
